import { Restaurant, Tag } from '@/types';

export const INITIAL_TAGS: Tag[] = [
  { id: 'tag-1', name: 'Bún / Phở' },
  { id: 'tag-2', name: 'Cơm tấm / Cơm nhà' },
  { id: 'tag-3', name: 'Lẩu & Nướng' },
  { id: 'tag-4', name: 'Cà phê & Bánh' },
  { id: 'tag-5', name: 'Ăn vặt' },
  { id: 'tag-6', name: 'Hải sản' },
  { id: 'tag-7', name: 'Món chay' },
  { id: 'tag-8', name: 'Nhà hàng gia đình' },
  { id: 'tag-9', name: 'Nhà hàng châu Á' },
  { id: 'tag-10', name: 'Quán ăn nhỏ' },
  { id: 'tag-11', name: 'Nhà hàng món chay' },
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'res-6',
    name: 'Cơm Tấm Phi',
    address: '27 Huỳnh Tấn Phát, Nhà Bè, Hồ Chí Minh, Việt Nam',
    latitude: 10.6975,
    longitude: 106.7458,
    rating: 4.8,
    note: 'Cơm tấm sườn bì chả nướng thơm lừng, bì giòn không ngấy, nước mắm kẹo đậm đà.',
    price_range: '40k - 65k',
    google_maps_url: 'https://maps.google.com/?q=27+Huynh+Tan+Phat+Nha+Be',
    is_favorite: true,
    cover_photo: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    tags: [INITIAL_TAGS[7], INITIAL_TAGS[1]],
  },
  {
    id: 'res-7',
    name: 'Cơm tấm ngô quyền',
    address: 'MPQR+MQC Cơm tấm ngô quyền, Huỳnh Tấn Phát, Nhà Bè, Hồ Chí Minh',
    latitude: 10.7021,
    longitude: 106.7412,
    rating: 4.0,
    note: 'Thịt ướp ngũ vị thơm lừng nướng than hoa, phục vụ nhanh, canh cải ngọt thanh.',
    price_range: '35k - 55k',
    google_maps_url: 'https://maps.google.com/?q=Com+tam+ngo+quyen+Nha+Be',
    is_favorite: false,
    cover_photo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    tags: [INITIAL_TAGS[8], INITIAL_TAGS[1]],
  },
  {
    id: 'res-8',
    name: 'quán cơm tấm cẩm ly',
    address: '2020/2 Huỳnh Tấn Phát, Khu phố 7, Nhà Bè, Hồ Chí Minh',
    latitude: 10.7042,
    longitude: 106.7385,
    rating: 5.0,
    note: 'Cơm tấm sườn cọng số 1 Nhà Bè, tóp mỡ giòn rụm, trứng ốp la lòng đào chảy béo ngậy.',
    price_range: '45k - 70k',
    google_maps_url: 'https://maps.google.com/?q=2020/2+Huynh+Tan+Phat+Nha+Be',
    is_favorite: true,
    cover_photo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
    tags: [INITIAL_TAGS[9], INITIAL_TAGS[1]],
  },
  {
    id: 'res-9',
    name: 'Cơm Chay Hoa Tâm',
    address: '2180 Huỳnh Tấn Phát, Nhà Bè, Hồ Chí Minh',
    latitude: 10.6931,
    longitude: 106.7512,
    rating: 4.1,
    note: 'Món chay thanh tịnh, nêm nếm vừa vặn tự nhiên, không gian sạch sẽ ấm cúng.',
    price_range: '30k - 50k',
    google_maps_url: 'https://maps.google.com/?q=2180+Huynh+Tan+Phat+Nha+Be',
    is_favorite: false,
    cover_photo: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    tags: [INITIAL_TAGS[10], INITIAL_TAGS[6]],
  },
  {
    id: 'res-1',
    name: 'Phở Bò Gia Truyền 1986',
    address: '45 Bát Đàn, Hoàn Kiếm, Hà Nội',
    latitude: 21.0336,
    longitude: 105.8475,
    rating: 5,
    note: 'Nước dùng trong và ngọt thanh từ xương hầm, thịt bò tái lăn mềm thơm. Nên đi sớm trước 8h sáng để không phải xếp hàng lâu.',
    price_range: '50k - 85k',
    google_maps_url: 'https://maps.google.com/?q=45+Bat+Dan+Ha+Noi',
    is_favorite: true,
    cover_photo: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&q=80',
    tags: [INITIAL_TAGS[0]],
  },
  {
    id: 'res-2',
    name: 'Cơm Tấm Ba Ghiền',
    address: '84 Đặng Văn Ngữ, Phú Nhuận, TP.HCM',
    latitude: 10.7937,
    longitude: 106.6713,
    rating: 5,
    note: 'Miếng sườn nướng than hoa to che kín cả đĩa cơm, ướp đậm đà mật ong sả, chả trứng bùi béo. Quán ruột mỗi trưa đói bụng.',
    price_range: '70k - 120k',
    google_maps_url: 'https://maps.google.com/?q=84+Dang+Van+Ngu+Phu+Nhuan',
    is_favorite: true,
    cover_photo: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
    tags: [INITIAL_TAGS[1]],
  },
  {
    id: 'res-3',
    name: 'Lẩu Bò Nhà Gỗ Ba Toa',
    address: '1 Hoàng Diệu, Phường 5, Đà Lạt',
    latitude: 11.9404,
    longitude: 108.4352,
    rating: 4,
    note: 'Trời se lạnh ngồi cạnh nồi lẩu bốc khói nghi ngút, thịt bắp bò và gân bò mềm sần sật, chấm chao sa tế cay nồng. Nhớ gọi thêm mì trứng.',
    price_range: '180k - 300k',
    google_maps_url: 'https://maps.google.com/?q=1+Hoang+Dieu+Da+Lat',
    is_favorite: true,
    cover_photo: 'https://images.unsplash.com/photo-1547496502-affa22d38842?w=800&q=80',
    tags: [INITIAL_TAGS[2]],
  },
  {
    id: 'res-4',
    name: 'Cà Phê Giảng',
    address: '39 Nguyễn Hữu Huân, Hoàn Kiếm, Hà Nội',
    latitude: 21.0322,
    longitude: 105.8546,
    rating: 5,
    note: 'Cà phê trứng trứ danh có từ 1946. Lớp kem trứng đánh bông ngậy đặc sánh, quyện cùng vị cà phê đắng đậm đà phía dưới, không hề bị tanh.',
    price_range: '35k - 60k',
    google_maps_url: 'https://maps.google.com/?q=39+Nguyen+Huu+Huan+Ha+Noi',
    is_favorite: true,
    cover_photo: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80',
    tags: [INITIAL_TAGS[3]],
  },
  {
    id: 'res-5',
    name: 'Bánh Tráng Cuốn Thịt Heo Hoàng Bèo',
    address: '40 Duy Tân, Cầu Giấy, Hà Nội',
    latitude: 21.0305,
    longitude: 105.7831,
    rating: 4,
    note: 'Thịt heo quay bì giòn rụm hoặc thịt luộc hai đầu da, rau rừng tươi xanh đa dạng, chấm mắm nêm Đà Nẵng thơm lừng.',
    price_range: '60k - 90k',
    google_maps_url: 'https://maps.google.com/?q=40+Duy+Tan+Cau+Giay',
    is_favorite: false,
    cover_photo: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80',
    tags: [INITIAL_TAGS[4]],
  },
];
